### ISSUE TITLE
[bug] won't compile with nginx 1.20.1 or 1.21.1

### ISSUE THREAD

**Issue by reedog117** [aileone/nginx-http-flv-module#1]
When you meet a bug, please open the issue including a title prefixed by '[bug]' and describe it as follows:

### Expected behavior

Successful compilation

### Actual behavior

```
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -Wimplicit-fallthrough=0  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /tmp/nginx-http-flv-module-1.2.6 -I objs -I src/http -I src/http/modules -I /tmp/nginx-http-flv-module-1.2.6 \
	-o objs/addon/nginx-http-flv-module-1.2.6/ngx_rtmp.o \
	/tmp/nginx-http-flv-module-1.2.6/ngx_rtmp.c
/tmp/nginx-http-flv-module-1.2.6/ngx_rtmp.c: In function 'ngx_rtmp_add_listening':
/tmp/nginx-http-flv-module-1.2.6/ngx_rtmp.c:812:7: error: 'ngx_listening_t' {aka 'struct ngx_listening_s'} has no member named 'post_accept_timeout'
  812 |     ls->post_accept_timeout = 60000;
      |       ^~
make[1]: *** [objs/Makefile:1358: objs/addon/nginx-http-flv-module-1.2.6/ngx_rtmp.o] Error 1
```

Seems similar to https://github.com/winshining/nginx-http-flv-module/issues/205

### Steps to reproduce the behavior 

Compile module with nginx 1.20.1 or 1.21.1
